version: "3.0"

services:
  database:
    container_name: db
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
    restart: always
    volumes:
      - mysql-data:/var/lib/mysql
    ports:
    - "3306:3306"
    networks:
      - app-network
  app:
    container_name: rest
    build: .
    ports:
    - "8080:8080"
    networks:
      - app-network

volumes:
  mysql-data:

networks:
  app-network:
    driver: bridge